export function buildEmailHTML(event) {
  return `
    <div style="font-family: Arial, sans-serif; padding: 16px;">
      <h2>Your Reminder</h2>
      <p><strong>Event:</strong> ${event.title}</p>
      <p><strong>Date:</strong> ${event.date}</p>
      <p><strong>Notes:</strong> ${event.notes || "None"}</p>
      <hr />
      <p style="color: gray; font-size: 12px;">
        This reminder was generated by your Event Reminder App.
      </p>
    </div>
  `;
}
